### PR TITLE
Main elements with content is added

### PR DESCRIPTION
**Pull request by bettercallazamat**
## Main elements are such as:
1) Header
2) Article
3) Aside
4) Suggested articles section
5) Footer

## Notes: 
1) Media queries and functionality is not applied
2) We have not enclosed each paragraph with p tag due to the following requirements of The Odin Project page: 7) Fill in and position the additional sections. Don’t worry about enclosing every paragraph of text in p tags.
3) We ignored left errors from Stickler because solving the errors will break the sequence of the HTML and CSS files.

### CODE REVIEW

**Comment by majovanilla** [comment]
### Code under review by Maria Reyes

**Comment by majovanilla** [comment]
Hey Team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯
I really liked the look of your page!

- Good Readme file
- Good Pull Request message
- Good Commit messages

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

**General corrections**

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors related to the `<p>` tag. Like you pointed out on the PR message, there is no need to enclose every paragraph in it, but that doesn't mean you can skip HTML rules. The rule says you can't have nested divs inside a paragraph tag (more info [here](https://stackoverflow.com/questions/21084870/no-p-element-in-scope-but-a-p-end-tag-seen-w3c-validation)), but you can nest other valid elements. Please fix those errors.
Screenshot from 2020-02-26 12-02-50

- The linters are a guide to help you write better code. The rules you are not taking into consideration are important when it comes to the C of CSS (which stands for Cascade). Your CSS will apply all styles from up to bottom (like a cascade). If an element is styled multiple times, the last rule will override the first one. 
BUT the way you have it right now is not respecting that cascading order since you have a more specific selector (id) BEFORE a more general selector (class). See more [here](https://stylelint.io/user-guide/rules/no-descending-specificity)
If you don't want to change the order of your files, I will suggest changing the id selector to a class selector, but you have to keep your checks green :heavy_check_mark: 

- You are using a great template for your ReadMe file, now take advantage of it! Improve the description of your project: include what it does, why you did it, details... this is a very good practice.


**Project specifics**

- Please make the NYT logo to be a link as it is in the original page.

- Include the hover effect on the bottom part links. It should change the text to gray like the original page.

- Include the hover effect on the footer links and the aside links. It should underline the text like the original page.

- You should include the links within the text, with the correct hover effect. See screenshots:
Your project:
Screenshot from 2020-02-26 13-41-52

Original page:
Screenshot from 2020-02-26 13-41-58

- Check the hover effects at the end of the article's text (comment section) and make them like the original page.


### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- You used semantic HTML in your file. You could also include a `<main>` tag to enclose the most important part of the content (not including the nav and the footer).


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. 

One more thing to change: `/imgs/18cosmos-2-superJumbo.jpg` is not displaying, because of missing dot in path to image. Please change that, than go ahead and merge to master.

_Goodluck in your next project_ *Happy coding*

**Pull request merged**
